### ISSUE TITLE
Read_hdf error

### ISSUE THREAD

**Issue by painday** [Memcys/DIY-Python#9]
It seems that one has to install python3.8 to properly use read_hdf method, otherwise the interpreter will raise an error. As an alternative solution,  a treatment of the original source file for the GRB exercise is required.
Ending here.

**Comment by Memcys** [comment]
I will follow https://stackoverflow.com/a/60895965 to provide a `hdf` data file with protocol 4.

See also pandas-dev/pandas#33087 for the same problem.

**Comment by painday** [comment]
The issue is closed for the bug has been fixed by @Memcys .
